import {canonicalUrlKey,isPublicHttpUrl} from '../core/url.js';
import {extractDocument} from '../index/content.js';
import {canCrawl} from './robots.js';
import {CrawlFrontier} from './frontier.js';

export class OmniCrawler{
  constructor({store,frontier=new CrawlFrontier('data/crawl-frontier.json'),fetchImpl=fetch,timeoutMs=8000,maxConcurrency=4,userAgent='OmniBot/1.0',onEvent}={}){this.store=store;this.frontier=frontier;this.fetchImpl=fetchImpl;this.timeoutMs=timeoutMs;this.maxConcurrency=maxConcurrency;this.userAgent=userAgent;this.onEvent=onEvent;}
  async seed(seeds){await this.frontier.init();for(const url of seeds)await this.frontier.enqueue(url,{priority:100});await this.frontier.flush();}
  async crawl(seeds=[],{maxPages=25,maxDepth=2,sameOrigin=true,recrawlDays=7}={}){await this.frontier.init();if(seeds.length)await this.seed(seeds);let indexed=0,changed=0,failed=0;while(indexed<maxPages){const batch=await this.frontier.claim(Math.min(this.maxConcurrency,maxPages-indexed));if(!batch.length)break;const results=await Promise.all(batch.map(item=>this.#visit(item).catch(error=>({error,item}))));for(const r of results){if(r.error){failed++;this.frontier.fail(r.item.key,r.error);this.onEvent?.({type:'error',url:r.item.url,error:String(r.error.message||r.error)});continue;}indexed++;const saved=await this.store.upsert(r.doc);if(saved.changed)changed++;const next=new Date(Date.now()+recrawlDays*86400000).toISOString();this.frontier.complete(r.item.key,{nextCrawlAt:next,hash:r.doc.hash});this.onEvent?.({type:saved.changed?'indexed':'unchanged',url:r.doc.url,title:r.doc.title,depth:r.item.depth,version:saved.doc.version});if(r.item.depth<maxDepth){const origin=new URL(r.doc.url).origin;for(const link of r.doc.links){try{if(sameOrigin&&new URL(link).origin!==origin)continue;}catch{continue}await this.frontier.enqueue(link,{depth:r.item.depth+1,priority:Math.max(1,100-r.item.depth*10),discoveredBy:r.doc.canonical});}}}}await this.frontier.flush();await this.store.flush();return {processed:indexed,changed,failed,frontier:this.frontier.stats(),index:this.store.stats()};}
  async #visit(item){if(!(await canCrawl(item.url,{fetchImpl:this.fetchImpl,timeoutMs:this.timeoutMs,userAgent:this.userAgent})))throw new Error('Blocked by robots.txt');const res=await this.fetchImpl(item.url,{redirect:'follow',headers:{'user-agent':this.userAgent,accept:'text/html,application/xhtml+xml'},signal:AbortSignal.timeout(this.timeoutMs)});if(!res.ok)throw new Error(`HTTP ${res.status}`);const type=res.headers.get('content-type')||'';if(!/text\/html|application\/xhtml\+xml/i.test(type))throw new Error('Not HTML');const html=await res.text();return {item,doc:extractDocument(html,res.url||item.url)};}
}
