import {TTLCache} from './core/cache.js';
import {CircuitBreaker} from './core/circuit.js';
import {OmniError} from './core/errors.js';
import {fuseResults} from './core/rank.js';
import {canonicalUrlKey,isPublicHttpUrl} from './core/url.js';
import {searchSerper,searchSerpApi,searchExa,searchSearxng,scrapeWithFirecrawl} from './providers/index.js';
import {analyzeQuery,queryFeatures} from './query/analyzer.js';
import {rankIndexed} from './index/rank.js';
import {rerankResults} from './ranking/engine.js';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,n));
export function normalizeQuery(query){const q=typeof query==='string'?query.replace(/\s+/g,' ').trim():'';if(!q)throw new OmniError('BAD_QUERY','Query is empty',400);if(q.length>300)throw new OmniError('BAD_QUERY','Query is too long (max 300 characters)',400);return q;}
export function buildProviders(config,fetchImpl){const shared=o=>({timeoutMs:config.providerTimeoutMs,fetchImpl,...o}),list=[];if(config.keys.serper)list.push({name:'serper',tier:'primary',run:(q,o)=>searchSerper(q,config.keys.serper,shared(o))});if(config.keys.serpapi)list.push({name:'serpapi',tier:'primary',run:(q,o)=>searchSerpApi(q,config.keys.serpapi,shared(o))});if(config.keys.exa)list.push({name:'exa',tier:'primary',run:(q,o)=>searchExa(q,config.keys.exa,shared(o))});if(config.searxngUrl)list.push({name:'searxng',tier:'fallback',run:(q,o)=>searchSearxng(q,config.searxngUrl,shared(o))});return list;}
export function createSearchEngine(config,deps={}){
 const providers=deps.providers??buildProviders(config,deps.fetchImpl),cache=deps.cache??new TTLCache({max:config.cacheMax,ttlMs:config.cacheTtlMs}),scrapeCache=deps.scrapeCache??new TTLCache({max:100,ttlMs:config.scrapeCacheTtlMs}),breaker=deps.breaker??new CircuitBreaker({threshold:config.breakerThreshold,cooldownMs:config.breakerCooldownMs}),inflight=new Map(),store=deps.store;
 async function callProvider(provider,q,ctx){const started=Date.now();if(breaker.isOpen(provider.name)){const s={name:provider.name,ok:false,skipped:true,count:0,ms:0,error:'circuit open'};ctx.providers[provider.name]=s;ctx.onProvider?.({provider:s,results:ctx.fuse()});return}try{const results=await provider.run(q,{num:ctx.num});breaker.success(provider.name);ctx.lists.push({source:provider.name,results});const s={name:provider.name,ok:true,count:results.length,ms:Date.now()-started};ctx.providers[provider.name]=s;ctx.onProvider?.({provider:s,results:ctx.fuse()});}catch(err){breaker.failure(provider.name);const s={name:provider.name,ok:false,count:0,ms:Date.now()-started,error:String(err?.message??err).slice(0,200)};ctx.providers[provider.name]=s;ctx.onProvider?.({provider:s,results:ctx.fuse()});}}
 async function execute(q,key,options){const started=Date.now(),num=clamp(Number(options.num)||10,1,20),limit=clamp(Number(options.limit)||20,1,50),analysis=queryFeatures(analyzeQuery(q));const ctx={num,lists:[],providers:{},onProvider:options.onProvider,fuse:()=>fuseResults(ctx.lists,{limit,weights:config.weights})};const primary=providers.filter(p=>p.tier!=='fallback'),fallback=providers.filter(p=>p.tier==='fallback');if(store){const own=rankIndexed(store.candidates(analysis.terms),analysis,{limit});if(own.length)ctx.lists.push({source:'omni-index',results:own.map(x=>({url:x.url,title:x.title,snippet:x.description||x.content?.slice(0,300),publishedAt:x.indexedAt,score:x.score,source:'omni-index'}))});}
 await Promise.all(primary.map(p=>callProvider(p,q,ctx)));if(!ctx.lists.some(l=>l.results.length)&&fallback.length)await Promise.all(fallback.map(p=>callProvider(p,q,ctx)));let results=ctx.fuse();if(analysis.site)results=results.filter(r=>{try{const host=new URL(r.url).hostname.toLowerCase();return host===analysis.site||host.endsWith(`.${analysis.site}`)}catch{return false}});results=rerankResults(results,analysis,{limit});const out={query:q,analysis:{intent:analysis.intent,terms:analysis.terms,phrases:analysis.phrases,site:analysis.site},results,providers:ctx.providers,cached:false,tookMs:Date.now()-started};if(out.results.length)cache.set(key,out);return out;}
 async function search(query,options={}){const q=normalizeQuery(query),num=clamp(Number(options.num)||10,1,20),limit=clamp(Number(options.limit)||20,1,50);const indexed=store?.stats?.().documents||0;if(!providers.length&&!indexed)throw new OmniError('NO_PROVIDERS','No search providers or Omni index are configured',503);const key=`${q.toLowerCase()}|${num}|${limit}|${store?.stats?.().documents||0}`;if(!options.fresh){const hit=cache.get(key);if(hit)return {...hit,cached:true,tookMs:0};const running=inflight.get(key);if(running)return running.then(r=>({...r,cached:true}));}const run=execute(q,key,options).finally(()=>{if(inflight.get(key)===run)inflight.delete(key)});inflight.set(key,run);return run;}
 async function scrape(url,options={}){if(!isPublicHttpUrl(url))throw new OmniError('BAD_URL','URL must be a public http(s) address',400);if(!config.keys.firecrawl)throw new OmniError('NO_SCRAPER','Page extraction is not configured',503);const key=canonicalUrlKey(url);if(!options.fresh){const hit=scrapeCache.get(key);if(hit)return {...hit,cached:true};}const page=await scrapeWithFirecrawl(url,config.keys.firecrawl,{timeoutMs:config.scrapeTimeoutMs,fetchImpl:deps.fetchImpl});scrapeCache.set(key,page);return {...page,cached:false};}
 return {search,scrape,providerNames:()=>providers.map(p=>p.name),indexStats:()=>store?.stats?.()??{documents:0,terms:0,words:0}};
}
